In [45]:
import pandas as pd

df = pd.read_csv('/Users/welldev/Code/self-development/python/module_2/pandas/data.csv')

In [52]:
print(df)

   id           name  age   department  salary   join_date
0   1       John Doe   28  Engineering   55000  2021-03-15
1   2     Jane Smith   34    Marketing   62000  2019-07-23
2   3    Bob Johnson   45        Sales   70000  2018-11-12
3   4    Alice Brown   29  Engineering   58000  2020-01-05
4   5  Charlie Davis   31           HR   50000  2022-06-30
5   6     Eve Wilson   38    Marketing   65000  2017-09-19
6   7   Frank Thomas   41        Sales   72000  2016-04-08

In [53]:
df.head() # First five rows

   id           name  age   department  salary   join_date
0   1       John Doe   28  Engineering   55000  2021-03-15
1   2     Jane Smith   34    Marketing   62000  2019-07-23
2   3    Bob Johnson   45        Sales   70000  2018-11-12
3   4    Alice Brown   29  Engineering   58000  2020-01-05
4   5  Charlie Davis   31           HR   50000  2022-06-30

In [ ]:
df.tail() # Lasst five rows

   id           name  age   department  salary   join_date
3   4    Alice Brown   29  Engineering   58000  2020-01-05
4   5  Charlie Davis   31           HR   50000  2022-06-30
5   6     Eve Wilson   38    Marketing   65000  2017-09-19
6   7   Frank Thomas   41        Sales   72000  2016-04-08
7   8      Grace Lee   26           HR   48000  2023-02-20

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          7 non-null      int64
 1   name        7 non-null      object
 2   age         7 non-null      int64
 3   department  7 non-null      object
 4   salary      7 non-null      int64
 5   join_date   7 non-null      object
dtypes: int64(3), object(3)
memory usage: 468.0+ bytes

In [49]:
df.describe()

             id        age        salary
count  7.000000   7.000000      7.000000
mean   4.000000  35.142857  61714.285714
std    2.160247   6.414270   7973.169293
min    1.000000  28.000000  50000.000000
25%    2.500000  30.000000  56500.000000
50%    4.000000  34.000000  62000.000000
75%    5.500000  39.500000  67500.000000
max    7.000000  45.000000  72000.000000

In [9]:
df.columns

Index(['id', 'name', 'age', 'department', 'salary', 'join_date'], dtype='object')

In [10]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [13]:
df["department"] # returns a series
set(df['department'])

{'Engineering', 'HR', 'Marketing', 'Sales'}

In [ ]:
df[['department', 'age']] # returns another dataframe

    department  age
0  Engineering   28
1    Marketing   34
2        Sales   45
3  Engineering   29
4           HR   31
5    Marketing   38
6        Sales   41
7           HR   26

In [15]:
df.iloc[1]

id                     2
name          Jane Smith
age                   34
department     Marketing
salary             62000
join_date     2019-07-23
Name: 1, dtype: object

In [ ]:
#df.iloc[1][1]
df.iloc[1]["name"]

/var/folders/lx/2hxxn9gn741cbc_6p_4whr5h0000gn/T/ipykernel_46236/2685484918.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[1][1]

'Jane Smith'

In [33]:
df[(df['department'] == 'Marketing') & (df['age'] < 35)]

   id        name  age department  salary   join_date
1   2  Jane Smith   34  Marketing   62000  2019-07-23

In [35]:
df[(df['salary']  < 60000) | (df['age'] < 35)]

   id           name  age   department  salary   join_date
0   1       John Doe   28  Engineering   55000  2021-03-15
1   2     Jane Smith   34    Marketing   62000  2019-07-23
3   4    Alice Brown   29  Engineering   58000  2020-01-05
4   5  Charlie Davis   31           HR   50000  2022-06-30
7   8      Grace Lee   26           HR   48000  2023-02-20

In [36]:
df[df['name'].str.startswith('J')]

   id        name  age   department  salary   join_date
0   1    John Doe   28  Engineering   55000  2021-03-15
1   2  Jane Smith   34    Marketing   62000  2019-07-23

In [ ]:
df[~df['name'].str.startswith('J')] # Reverses the condition, returns the result that doesn't match the condition

   id           name  age   department  salary   join_date
2   3    Bob Johnson   45        Sales   70000  2018-11-12
3   4    Alice Brown   29  Engineering   58000  2020-01-05
4   5  Charlie Davis   31           HR   50000  2022-06-30
5   6     Eve Wilson   38    Marketing   65000  2017-09-19
6   7   Frank Thomas   41        Sales   72000  2016-04-08
7   8      Grace Lee   26           HR   48000  2023-02-20

In [41]:
df.loc[df['name'] == 'Jane Doe']

   id      name  age department  salary   join_date
1   2  Jane Doe   34  Marketing   62000  2019-07-23

In [39]:
df.loc[df['name'] == 'Jane Smith', 'name'] = 'Jane Doe'

In [ ]:
df['name'] = df['name'].str.upper() # Will change every name into uppercase

In [46]:
df = df.drop(7)

In [ ]:
df.dropna() # Drops null values
df.fillna({"salary": 30000}, inplace=True)

In [55]:
df.rename(columns={"join_date": "joining_date"}, inplace=True)

In [57]:
df['department'].value_counts()

department
Engineering    2
Marketing      2
Sales          2
HR             1
Name: count, dtype: int64

In [59]:
df.groupby('department')['salary'].sum()
df.sort_values('salary', ascending=False)

   id           name  age   department  salary joining_date
6   7   Frank Thomas   41        Sales   72000   2016-04-08
2   3    Bob Johnson   45        Sales   70000   2018-11-12
5   6     Eve Wilson   38    Marketing   65000   2017-09-19
1   2     Jane Smith   34    Marketing   62000   2019-07-23
3   4    Alice Brown   29  Engineering   58000   2020-01-05
0   1       John Doe   28  Engineering   55000   2021-03-15
4   5  Charlie Davis   31           HR   50000   2022-06-30

In [60]:
df.to_csv('new_data.csv')