In [2]:
import pandas as pd

df = pd.read_csv('/Users/welldev/Code/self-development/python/module_2/pandas/data.csv')

In [4]:
print(df)

   id           name  age   department  salary   join_date
0   1       John Doe   28  Engineering   55000  2021-03-15
1   2     Jane Smith   34    Marketing   62000  2019-07-23
2   3    Bob Johnson   45        Sales   70000  2018-11-12
3   4    Alice Brown   29  Engineering   58000  2020-01-05
4   5  Charlie Davis   31           HR   50000  2022-06-30
5   6     Eve Wilson   38    Marketing   65000  2017-09-19
6   7   Frank Thomas   41        Sales   72000  2016-04-08
7   8      Grace Lee   26           HR   48000  2023-02-20

In [ ]:
df.head() # First five rows

   id           name  age   department  salary   join_date
0   1       John Doe   28  Engineering   55000  2021-03-15
1   2     Jane Smith   34    Marketing   62000  2019-07-23
2   3    Bob Johnson   45        Sales   70000  2018-11-12
3   4    Alice Brown   29  Engineering   58000  2020-01-05
4   5  Charlie Davis   31           HR   50000  2022-06-30

In [ ]:
df.tail() # Lasst five rows

   id           name  age   department  salary   join_date
3   4    Alice Brown   29  Engineering   58000  2020-01-05
4   5  Charlie Davis   31           HR   50000  2022-06-30
5   6     Eve Wilson   38    Marketing   65000  2017-09-19
6   7   Frank Thomas   41        Sales   72000  2016-04-08
7   8      Grace Lee   26           HR   48000  2023-02-20

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          8 non-null      int64
 1   name        8 non-null      object
 2   age         8 non-null      int64
 3   department  8 non-null      object
 4   salary      8 non-null      int64
 5   join_date   8 non-null      object
dtypes: int64(3), object(3)
memory usage: 516.0+ bytes

In [8]:
df.describe()

            id        age        salary
count  8.00000   8.000000      8.000000
mean   4.50000  34.000000  60000.000000
std    2.44949   6.761234   8831.760866
min    1.00000  26.000000  48000.000000
25%    2.75000  28.750000  53750.000000
50%    4.50000  32.500000  60000.000000
75%    6.25000  38.750000  66250.000000
max    8.00000  45.000000  72000.000000

In [9]:
df.columns

Index(['id', 'name', 'age', 'department', 'salary', 'join_date'], dtype='object')

In [10]:
df.index

RangeIndex(start=0, stop=8, step=1)